api_version = "2025-10"
[[extensions]]
name = "t:name"
handle = "build-your-basket"
type = "ui_extension"
uid = "f1519eb4-47e2-30f0-3981-e446be0610eccffbaf98"

# Both extension points are required
[[extensions.targeting]]
module = "./src/ProductDetailsConfigurationExtension.jsx"
target = "admin.product-details.configuration.render"
[extensions.targeting.urls]
edit = "/bundles/products/{product_id}"


[[extensions.targeting]]
module = "./src/ProductVariantDetailsConfigurationExtension.jsx"
# The target used here must match the target used in the module file (./src/ProductVariantDetailsConfigurationExtension.jsx)
target = "admin.product-variant-details.configuration.render"
